# Generated by Django 4.0.2 on 2022-02-15 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horoscope', models.CharField(choices=[('CA', 'Capricorn'), ('TA', 'Taurus'), ('GE', 'Gemini'), ('CA', 'Cancer'), ('LE', 'Leo'), ('VI', 'Virgo'), ('LI', 'Libra'), ('SC', 'Scorpio'), ('SA', 'Sagittarius'), ('AQ', 'Aquarius'), ('PI', 'Pisces')], default='CAPRICORN', max_length=2)),
                ('profile_pic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
