# Generated by Django 4.0.2 on 2022-02-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_profile_horoscope_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscope',
            name='horoscope',
            field=models.CharField(choices=[('CA', 'Capricorn'), ('TA', 'Taurus'), ('GE', 'Gemini'), ('CA', 'Cancer'), ('LE', 'Leo'), ('VI', 'Virgo'), ('LI', 'Libra'), ('SC', 'Scorpio'), ('SA', 'Sagittarius'), ('AQ', 'Aquarius'), ('PI', 'Pisces')], default='Capricorn', max_length=2),
        ),
    ]
