# Generated by Django 4.0.2 on 2022-02-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_horoscope_text_alter_horoscope_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscope',
            name='text',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
