# Generated by Django 4.0.2 on 2022-02-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_horoscope_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscope',
            name='text',
            field=models.CharField(default='', max_length=25),
        ),
    ]
